function gen_plot_eror_sims(connections,...
                            image_size_mat,...
                            partitions_N,...
                            series_resistance,...
                            subFighdl,...
                            color_spec,...
                            sel_connection,...
                            titleStr,...
                            memdiode_model_array,...
                            plot_fresh_reference)
                        
    line_spec={'-','--','-.',':'};
    line_width=2.0;        
    str2rgb=@(x)get(line('color',x),'color');
    color_spce_vec=str2rgb(color_spec);
    mode_plot='error';
    
    axis(subFighdl);
    for connections_i=1:size(connections,2)
        if isfield(connections{1,connections_i},'CPA_size') && connections_i==sel_connection
            for image_size_mat_idx=1:size(image_size_mat,1)
                    if size(connections{1,connections_i}.CPA_size{1,image_size_mat_idx},1)>0 && size(connections{1,connections_i}.CPA_size{1,image_size_mat_idx},2)>0
                        for Rs_i=1:length(series_resistance)
                            if strcmpi(mode_plot,'error')
                                if Rs_i<=size(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_error_gral,1) && ~all(isnan(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_error_gral(Rs_i,:)))
                                    x_nZ=find(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.fault_ratio~=0);
                                    errorbar(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.fault_ratio(x_nZ),...
                                            (1-connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_error_gral(Rs_i,x_nZ))*100,...
                                            connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.std_error_gral(Rs_i,x_nZ)*100,...
                                            'Color',([1 1 1]-(([1 1 1]-color_spce_vec))*0.5),...  %
                                            'LineStyle',line_spec{1,1},...
                                            'LineWidth',line_width,...
                                            'DisplayName',sprintf('NP=%d, R_S=%.2g\\Omega', partitions_N, series_resistance(Rs_i)));
                                    if Rs_i==1
                                        hold on
                                        ylabel('Mean CPA Inference Accuracy [\%]','Interpreter','latex');
                                        xlabel('ratio of faulty devices [a.u.]','Interpreter','latex');
                                        title({memdiode_model_array{1,1} titleStr},'Interpreter','none');
                                        axis([0 0.95 0 105]);
                                        grid minor
                                    end
                                    plot(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.fault_ratio(x_nZ),...
                                            (1-connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_error_gral(Rs_i,x_nZ))*100,...
                                            'Color',color_spec,...
                                            'LineStyle',line_spec{1,1},...
                                            'LineWidth',line_width,...
                                            'DisplayName',sprintf('NP=%d, R_S=%.2g\\Omega', partitions_N, series_resistance(Rs_i)));
                                    x = [0 0.95];
                                    y = [1 1]*(1-connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_error_gral(Rs_i,1))*100;
                                    if plot_fresh_reference==1
                                        plot(x,...
                                             y,...
                                             'Color',color_spec,...
                                             'LineStyle','--',...
                                             'LineWidth',line_width);
                                        text(x(2)-0.05,...
                                            y(1)-0.05,...
                                            sprintf('%.1f%%',(1-connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_error_gral(Rs_i,1))*100),...
                                            'BackgroundColor', 'white');
                                    end
                                end
                            elseif strcmpi(mode_plot,'SWV')
                                if Rs_i<=size(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_error_gral,1) && ~all(isnan(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_error_gral(Rs_i,:)))
                                    x_nZ=find(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.fault_ratio~=0);
                                    errorbar(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.fault_ratio(x_nZ),...
                                            connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_SWV(Rs_i,x_nZ),...
                                            connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.std_SWV(Rs_i,x_nZ),...
                                            'Color',([1 1 1]-(([1 1 1]-color_spce_vec))*0.5),...  %
                                            'LineStyle',line_spec{1,1},...
                                            'LineWidth',line_width,...
                                            'DisplayName',sprintf('NP=%d, R_S=%.2g\\Omega', partitions_N, series_resistance(Rs_i)));
                                    if Rs_i==1
                                        hold on
                                        ylabel('Mean CPA Inference Accuracy [\%]','Interpreter','latex');
                                        xlabel('ratio of faulty devices [a.u.]','Interpreter','latex');
                                        title({memdiode_model_array{1,1} titleStr},'Interpreter','none');
                                        axis([0 0.95 0 500]);
                                        grid minor
                                    end
                                    plot(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.fault_ratio(x_nZ),...
                                            connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_SWV(Rs_i,x_nZ),...
                                            'Color',color_spec,...
                                            'LineStyle',line_spec{1,1},...
                                            'LineWidth',line_width,...
                                            'DisplayName',sprintf('NP=%d, R_S=%.2g\\Omega', partitions_N, series_resistance(Rs_i)));
                                    x = [0 0.95];
                                    y = [1 1]*(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_SWV(Rs_i,1));
                                    if plot_fresh_reference==1
                                        plot(x,...
                                             y,...
                                             'Color',color_spec,...
                                             'LineStyle','--',...
                                             'LineWidth',line_width);
                                        text(x(2)-0.05,...
                                            y(1)-0.05,...
                                            sprintf('%.1f%%',(connections{1,connections_i}.CPA_size{1,image_size_mat_idx}.mean_SWV(Rs_i,1))),...
                                            'BackgroundColor', 'white');
                                    end
                                end
                            end
                        end
                    end
            end 
            %legend('Location','eastoutside');
        end
    end

end